#ifndef MODELCOLUMNINDEXES
#define MODELCOLUMNINDEXES

#define PACKET_NUMBER_COLUMN_INDEX            0
#define TIME_RECIEVED_COLUMN_INDEX            1
#define SOURCE_ADDRESS_COLUMN_INDEX           2
#define DESTINATION_ADDRESS_COLUMN_INDEX      3
#define BINARY_DATA_SIZE_COLUMN_INDEX         4  //The size of the binary data pointed to by PACKET_NUMBER_COLUMN_INDEX - 1
#define HIGHEST_LEVEL_PROTOCOL_COLUMN_INDEX   5
#define INFORMATION_COLUMN_INDEX              6



#endif // MODELCOLUMNINDEXES